language: groovy

services:
  - docker

before_script:
  - chmod +x gradlew
  - ./gradlew cleanTest test

script: ./gradlew build

after_success:
  - docker build -t esuau/microservice-deploy:latest .
  - echo $DOCKER_PASSWORD | base64 --decode | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push esuau/microservice-deploy:latest
