language: groovy

services:
  - docker

install: true

before_script:
  - chmod +x gradlew
  - ./gradlew cleanTest test

script: ./gradlew build

after_success:
  - docker build -t esuau/microservice-deploy:latest .
  - echo $DOCKER_PASSWORD | base64 --decode | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push esuau/microservice-deploy:latest

before_deploy:
  - curl https://cli-assets.heroku.com/install.sh | sh

deploy:
  - provider: script
    script:
      /usr/local/bin/heroku container:push web
      /usr/local/bin/heroku container:release web
  on:
    branch: master
