version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew cleanTest test
  publish:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    working_directory: /src
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/distributions
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: docker build -t esuau/microservice-deploy:latest .
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push esuau/microservice-deploy:latest

workflows:
  version: 2
  test:
    jobs:
      - test
      - publish:
          requires:
            - test
