version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew cleanTest test
  publish:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/distributions
      - run: docker build -t esuau/microservice-deploy .
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push esuau/microservice-deploy

workflows:
  version: 2
  test:
    jobs:
      - test
      - publish:
          requires:
            - test
