name: Build and publish

on: [push]

jobs:
  groovy:
    name: Build Groov app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew cleanTest test
      - name: Build fat JAR
        run: ./gradlew build
  docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
      - uses: actions/docker/login@master
        with:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
      - name: Build Docker image
      - uses: actions/docker/cli@master
        with:
          args: build -t docker.pkg.github.com/esuau/microservice-deploy/microservice-deploy:latest .
      - name: Publish image to GitHub registry
      - uses: actions/docker/cli@master
        with:
          args: push docker.pkg.github.com/esuau/microservice-deploy/microservice-deploy:latest
