name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        chmod +x gradlew
        ./gradlew :cleanTest :test
    - name: Build fat JAR
      run: ./gradlew build
