name: Build and publish

on: [push]

jobs:
  test:
    name: Run app tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew cleanTest test
  publish:
    name: Build and publish Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build fat JAR
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Build and publish image to GitHub registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/esuau/microservice-deploy/microservice-deploy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
